deploy pado-node with docker
pado-labs/pado-network pull request #14
Opened 2024-05-28 06:59 UTC by xudean

2024-05-28 08:23 UTC, fksyuan requested changes

2024-05-28 08:23 UTC, fksyuan commented on padonode/Dockerfile
> +RUN npm install --save @padolabs/pado-ao-sdk
This should be npm install

2024-05-28 08:23 UTC, fksyuan commented on padonode/README_DOCKER.md
CONFIG_PATH_ON_HOST, CONFIG_PATH_IN_CONTAINER, KEY_FILE_PATH_IN_CONTAINER, etc. These variables can have a default value

2024-05-28 09:27 UTC, xudean commented on padonode/Dockerfile
> +RUN npm install --save @padolabs/pado-ao-sdk
modified

2024-05-28 09:28 UTC, xudean commented on padonode/README_DOCKER.md
Because of the need for compatibility with the suffix parameter being in the form of an path, if the default value is used, then only the configuration of the environment variable takes effect

2024-05-29 01:29 UTC, fksyuan approved these changes

2024-05-29 01:29 UTC, merged